spring.application.name=teste


# configuração do banco
spring.datasource.url=jdbc:h2:mem:teste
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# configuração JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# console web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:~/test

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=create-drop